- index.js
there's no reason to not use strict mode in 2016.
> <3 Strict mode FTW <3

- index.js
https://en.wikipedia.org/wiki/Thirteen_(House)
> Add support for Remy "Thirtheen" Hadley from House M.D

- index.js
Gotta make sure we check for lowercase thirteen
> Lowercase thirteen felt left out

- index.js
> Russian localization implemented

- README.md
> Added gitter

- index.js
- test.js
> Binary support

- index.js
- package.json
It now uses the syntax as described in #19.
We need to write tests now.
Closes #20
Closes #19
Closes #29
Closes #5
> Added better syntax

- index.js
Some reformatting of the code because the code styling used in #34 was really horrible and inconsistent.
> Reformatted code

- README.md
Linking to logo creator's github profile, extending description, link to the WTFPL license.
`is(prDescriptionWords).thirteen(); // true`
> Updating README with links, and extended package description.

- index.js
- test.js
I tried implementing this in my application but had trouble when passing imaginary thirteens. I've patched this and also added some imaginary unit tests.
> Added support for imaginary thirteens

- index.js
- test.js
[The real 13](http://images.teamsugar.com/files/upl0/1/13839/05_2008/house402_scene-13_7741_f.preview.jpg)
> Add support for Olivia Wilde

- index.js
- test.js
Source: Native Hebrew speaker and fluent in German
Including tests
> Added support for Hebrew and German strings

- index.js
- test.js
Fair warning that most have not been tested, happy to add in tests if anyone would like them.
> i18n improvements, enabling people around the world to enjoy 13

- .gitignore
- index.js
> implemented - not thirteen, divisible by thirteen, semicolons, maltese

- index.js
- test.js
Needs more folk rock hits from 1972
> Add Thirteen by Big Star

- .editorconfig
With a load of different editors out to there, we want to avoid inconsistency.
> Add editorconfig to maintain consistent coding styles

- index.js
- test.js
Trying to be professional and added few more test case,
So now even GOOGLE and NASA can use this library
> Fix all broken test and add new test

- .travis.yml
They unit test were broken. We should monitor them in Travis CI.
> Run tests in travis-ci

- index.js
> Add support for ‘B' == 13 fixing #157

- index.js
- test.js
> Add support for the best Johnny Cash's song

- index.js
Add Chinese Traditional 13 in upper case
FYI : https://zh.wikipedia.org/wiki/13
> Add Chinese Traditional 13 in upper case

- index.js
- test.js
Cebuano (or Bisaya) is one of the main languages in the Philippines, and is the most widely spoken language in the Visayan subgroup.
> Add Cebuano support

- index.js
> Fix broken link

- index.js
- test.js
got the issue number right this time guys I promise
> Added support for 'I3','l3' and '|3' #183

- index.js
- test.js
It was incorrectly translated.
> Fixed Irish word for "thirteen" and added Klingon translation

- index.js
> Dr. Hadley is not a he

- index.js
- test.js
Patty Tsai (蔡依珊) - Her first name sounds like "13" in Chinese.
She's be known as the wife of Taiwan Trump.
Her husband also claimed "start from scratch".
> Add Patty Tsai into thirteen strings

- index.js
- test.js
- Remove whitespaces
- Add wikipedia because they're thirteen (see link added)
- Added Philippine Tagalog version of Thirteen
All my added commits has a test case added, thanks!
> Tagalog Version and Added wikipedia because they're Thirteen

- test.js
β kinda looks like 13. We don't want to shortchange the users.
> Added β because it looks like 13

- test.js
Added unit tests for Nepali and devanagari. (Explanation in Nepali following)
आमा, म अमेरिका राम्ररी आइपुगें । अरु सब बेसै छ, चिट्ठी पठाउने पैसा नभएकाले एता बाटै बात गर्दा बेस होला जस्तो देखें । बालाई नि सम्झेको छ भन्दिनु । तपाइंको छोरो , पुन्टे
> Added unit tests for Nepali and Devanagari.

- README.md
- index.js
Tell if two numbers can add/subtract to 13.
is(4).plus(5).thirteen();      // false
is(12).plus(1).thirteen();    // true
is(4).minus(12).thirteen();    // false
is(14).minus(1).thirteen();    // true
> Plus and Minus Functionality

- index.js
Ref:
https://www.google.ca/search?q=dilma+13
> add Dilma 13 - President of Brazil

- index.js
Checks if thirteen can be spelled from given string or is an anagram of given string
> Rebased, added canSpell and anagramOf

- index.js
Implements the the highly sought after backwards integer input functionality.
Behold:
> is(13).backwards.thirteen();
false
> is(31).backwards.thirteen();
true
> backwards-integer-input-functionality-implementation-mechanism

- index.js
> remove magic numbers

- consts.js
- is.js
- test.js
Should take care of adding in literal strings for every possible base type between 2 and 36.
> comparison for all base types

- consts.js
and all the the different inflections of "þrettán"
> Added icelandic string support

- index.js
- test.js
Monkey might not know the number characters but it could use a symbol to count as 13.
e.g. '|||||||||||||'
> Support monkey to use

- .npmignore
> Added npmignore to make our npm installs faster

- consts.js
forgot some inflections in previous pull request
this should be all of them
> Icelandic strings support

- consts.js
- test.js
> Add cs_CZ locale

- consts.js
- test.js
Yup, Polish is easy and totally not complicated.
I hope I didn't miss any variant.
> Add more Polish 🇵🇱 variants

- consts.js
Just a simple update, to contribute with this project.
:smile:
> Update about current situation of president Dilma.

- .travis.yml
> travis: remove iojs

- consts.js
- test.js
> Added : French ordinal form

- consts.js
https://en.wikipedia.org/wiki/Hexadecimal
> add Hexadecimal

- consts.js
Add Kazakh language in conts.js.
> Add kazakh 13

- consts.js
- test.js
- In Korean, '십삼' also means 13.
> Add Korean '십삼'

- consts.js
> Arabic feminine form

- consts.js
> added emoji to thirteenStrings 

- test.js
This fixes a small typo in one of comments
> Fixed typo

- README.md
First of all, thank you for this wonderful project. The thing bothering me was the inconsistent spacing in the readme file. I hope that this helps future users
> very important: fixed inconsistent spacing

- consts.js
> Add 1.3 to 13 strings

- consts.js
- test.js
Hi. 
Please merge. 
Any additional questions, don't refrain to ask.
> Added support for the videogame XIII

- is.js
The previous version just blatantly lies
> Fix confusing comment

- is.js
> Aluminum's atomicNumber is 13.

- Assembler.oldSchool
> Fun with assembler

- consts.js
- test.js
If only there were more thirteens.
[13/13/13 (2013)](https://www.imdb.com/title/tt2991516/)
> Add 13/13/13 (2013).

- consts.js
- test.js
Copy and pasted from: https://www.web2generators.com/text-related-tools/write-upside-down
Flipping each character individually: "ƖƐ"
Flipping the characters together: "ƐƖ"
> Add flipped characters

- consts.js
- test.js
Support for the l33t way of writing on the internet.
> Support for 7h1r733n

- consts.js
Another potential match for thirteen.
> Added a 13 definition

- consts.js
> Added 13th Amendment

- is.js
Changes code to be consistent with the rest.
This is my first open source pull request.  : )
> Changes integers of 13 to THIRTEEN constant

- consts.js
- Adding more Korean variants like reading English word in Korean, combination with numbers, and etc.
- Adding regular expression for pronunciation that sounds thirteen in Korean.
> [Update] Adding more Korean variants

- consts.js
- test.js
I have added [Roman Urdu](https://en.wikipedia.org/wiki/Roman_Urdu) variant of 13 in constants
Proof: https://www.google.com/search?q=roman+urdu+tayra
> Add Roman Urdu variant

- consts.js
Adding another Tamil option to increase coverage
> adding more Tamil

- README.md
> Update yearOfBirth example
